Space girl copilot
GDCASU/Firefox pull request #74
Opened 2021-02-06 20:19 UTC by mattcorey5

Sorry this took so long for a pretty small task. I wasn't able to make it to the club meeting yesterday but I figured I should make a pull request for what I have. I created 2 new scripts, one for the SpaceGirl active and one for the passive. I also created a prefab for the SpaceGirl copilot. The passive and the active work as intended, but the way I implemented the passive could probably be better. The passive script adds/subtracts a specific damage value directly from PlayerInfo.singleton.bulletDamage using a boolean to make sure it only happens once. This was the only way I could think of that would still allow for multiple damage increases on the player at a time. Let me know whatever I need to fix and I will.

2021-02-10 22:31 UTC, propredator23 requested changes
Do the changes and let me know if you need help with the subscribing method part

2021-02-10 22:31 UTC, propredator23 commented on Assets/Scripts/CopilotMechanics/SpaceGirlPassive.cs
> +    private void Update()
Remove the Update Method and instead create a Method called CheckPassiveActivation,  in here you will check if the Player health is currently lower than the threshold, and if so you will call the AddEffect method in PlayerInfo where you will pass in a SatusEffect of type Focus, the damage increase variable, and the Timer Effect variable. You will need to subscribe this method to the PlayerInfo damageEvent. Check the MushRoomFriendPassive script  on the Start method line 16 to learn how to do this.

2021-02-19 22:03 UTC, nicholasngoc approved these changes
Good stuff 👍

2021-02-19 22:07 UTC, propredator23 approved these changes

2021-02-19 22:07 UTC, merged